### ISSUE TITLE
change text styling of About section

### ISSUE THREAD

**Issue by lloydlobo** [lloydlobo/gatsbynetlify#7]
## TODO
- [ ] Change `<h3>` to match the emphasized "description" of About section
- [ ] Remove the emojis except the first one on each bullet points

**Comment by RishiKumarRay** [comment]
where can i find this ? i tried , also i hope it is open for contributions

**Comment by lloydlobo** [comment]
> where can i find this ? i tried , also i hope it is open for contributions

Hey there @RishiKumarRay ! 👋

Added the URL in the About section. And yes, it's open for contribution. 🚀
In case you encounter any trouble, please let me know. 😀

**Comment by RishiKumarRay** [comment]
@lloydlobo Hi, where i can find the code that needs changes , thanks

**Comment by lloydlobo** [comment]
> @lloydlobo Hi, where i can find the code that needs changes , thanks

So when you fork the repo, you'll find it in the folder /src/'@lekoarts'/gatsby-theme-cara/about.mdx

The file to be modified is about.mdx. 

If you have any ideas or suggestions, feel free to make separate commits. Thanks. I am curious to know what you'll do with it. 

![IMG_20220202_103819.jpg](https://user-images.githubusercontent.com/76430758/152096494-7dcc9033-49d5-41a1-9466-164b45ca2fb4.jpg)
